# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'0', b'INACTIVE'), (b'1', b'ACTIVE')], default=b'1', help_text=b'Category Status', max_length=2)),
                ('parent_url', models.CharField(blank=True, help_text=b'Parent URL', max_length=128, null=True)),
                ('child_url', models.CharField(blank=True, help_text=b'Child URL', max_length=128, null=True)),
                ('content', models.TextField(blank=True, help_text=b'URL content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
