# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aue', '0002_enquirydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='url',
            field=models.CharField(blank=True, help_text=b'URL', max_length=128, null=True),
        ),
    ]
