# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aue', '0004_auto_20160319_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enquirydetails',
            unique_together=set([('parent_url', 'child_url', 'url', 'content')]),
        ),
    ]
