# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aue', '0005_auto_20160327_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='page_content',
            field=models.TextField(blank=True, help_text=b'Page Content', null=True),
        ),
    ]
